[package]
name = "gameboi"
version = "0.1.0"
authors = ["Steve James <0x2t1ff@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "0.120.0"
sdl2 = "0.34.5"
